title: BBQ Raiding
description: FFxiv BBQ FC Raiding
theme: just-the-docs

url: https://rollo8638.github.io/BBQ-Raiding/

color_scheme: dark

enable_copy_code_button: true

aux_links_new_tab: true  
aux_links:
  Github Repository: https://github.com/rollo8638/BBQ-Raiding/
  Discord: https://discord.gg/mCxu9CXbhT
  FFxiv FC page: https://na.finalfantasyxiv.com/lodestone/freecompany/9233505136016493098/

back_to_top: true
#back_to_top_text: "Back to top"