title: BBQ Raiding
description: 
theme: just-the-docs

url: https://rollo8638.github.io/BBQ-Raiding/

color_scheme: dark
  
aux_links:
  Github Repository: https://github.com/rollo8638/BBQ-Raiding/
  Discord: https://discord.gg/mCxu9CXbhT
  FFxiv FC page: https://na.finalfantasyxiv.com/lodestone/freecompany/9233505136016493098/